# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/vendor/cirrus/audio/dlkm/include

KBUILD_OPTIONS += $(EXTRA_CFLAGS)

ifneq (,$(filter ironmn% felix%, $(TARGET_PRODUCT)))
ifneq ($(filter m y,$(CONFIG_SND_SOC_CS35L45_I2C)),)
cirrus_cs35l45-objs = cs35l45.o cs35l45-tables.o wm_adsp.o cs35l45-i2c.o
else
cirrus_cs35l45-objs = cs35l45.o cs35l45-tables.o wm_adsp.o cs35l45-spi.o
endif
cirrus_cs42l42-objs = cs42l42.o
obj-m += cirrus_cs35l45.o cirrus_cs42l42.o
endif
